api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
rest: 
  type: rest 
  resource: "routing_rest.yml"
  prefix: /api
