security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_CLIENTE:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern: ^/central
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /central/home
                login_path: /central
                check_path:  fos_user_security_check
            logout:
                path: fos_user_security_logout
                target: central_homepage
            #logout:       true
            anonymous:    true

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/central/?$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/central/home/?$, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_CLIENTE] }
        - { path: ^/central/home/, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_CLIENTE] }