fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: central/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: central/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: central/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: central/profile

#fos_user_security_login:
#    pattern: central-do-cliente
#    defaults: { _controller: FOSUserBundle:Security:login }
    
fos_user_security_check:
    path: central/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: central/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Page:index }

central_homepage:
    path:     /central
    defaults: { _controller: CentralBundle:Page:index }
    
central_homepage_index:
    path:     /central/home
    defaults: { _controller: CentralBundle:Page:home }