#pais : 
#  type: rest
#  resource:     "CircularSiteBundle:PaisRest"
#  name_prefix:  api_

circular_api_get_token:
    pattern: /{id}/token/{tipo}/{versao}
    defaults: {_controller: ApiBundle:CircularRest:getToken, tipo: -1, versao: -1}
  
circular_api_get_dados:
    pattern: /recebe-dados/{hash}/{data}/{id}
    defaults: {_controller: ApiBundle:CircularRest:getDados, id: -1}
    
circular_api_set_dados:
    pattern: /envia-dados/{hash}
    defaults: {method: POST, _controller: ApiBundle:CircularRest:setDados}
    
circular_api_valida_token:
    pattern: /valida-token
    defaults: {_controller: ApiBundle:CircularRest:validaToken}
    
circular_api_set_imagem:
    pattern: /envia-imagem/{hash}
    defaults: {method: POST, _controller: ApiBundle:CircularRest:setImagem}
    
circular_api_get_imagem:
    pattern: /recebe-imagem/{nome}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getImagem}
    
circular_api_get_preferencias:
    pattern: /recebe-preferencias/{id}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getPreferencias}
    
circular_api_valida_usuario:
    pattern: /valida-usuario
    defaults: {_controller: ApiBundle:CircularRest:validaUsuario}
    
## API INTERNA ##

# EMPRESA
circular_api_get_empresas:
    pattern: /empresas/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getEmpresas, slug: ''}

# CIDADE
circular_api_get_cidades:
    pattern: /cidades/{uf}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getCidades, uf: '', slug: ''}

# BAIRRO
circular_api_get_bairros:
    pattern: /bairros/{uf}/{cidade}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getBairros, uf: '', cidade: '', slug: ''}

# PARADA
circular_api_get_paradas:
    pattern: /paradas/{uf}/{cidade}/{bairro}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getParadas, uf: '', cidade: '', bairro: '', slug: ''}

# PONTO INTERESSE    
circular_api_get_pontos_interesse:
    pattern: /pontos-interesse/{uf}/{cidade}/{bairro}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getPontosInteresse, uf: '', cidade: '', bairro: '', slug: ''}

# ITINERARIO
circular_api_get_itinerarios_parada_por_id:
    pattern: /paradas-id/{id}/itinerarios
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getItinerariosParadaPorId, id: ''}
    
circular_api_get_itinerarios_parada:
    pattern: /paradas/{uf}/{cidade}/{bairro}/{slug}/itinerarios
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getItinerariosParada, uf: '', cidade: '', bairro: '', slug: ''}
    
circular_api_get_paradas_itinerario:
    pattern: /itinerarios/{itinerario}/paradas
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getParadasItinerario, itinerario: ''}

# HORARIO
circular_api_get_horarios_itinerario:
    pattern: /horarios/{itinerario}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getHorariosItinerario, itinerario: ''}
    
circular_api_get_proximo_horario_itinerario:
    pattern: /horarios/{itinerario}/proximo/{hora}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getProximoHorarioItinerario, itinerario: '', hora: ''}
    
circular_api_get_horario_anterior_itinerario:
    pattern: /horarios/{itinerario}/anterior/{hora}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getHorarioAnteriorItinerario, itinerario: '', hora: ''}

circular_api_get_primeiro_horario_itinerario:
    pattern: /horarios/{itinerario}/primeiro/{dia}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getPrimeiroHorarioItinerario, itinerario: '', dia: ''}
    
circular_api_get_ultimo_horario_itinerario:
    pattern: /horarios/{itinerario}/ultimo/{dia}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getUltimoHorarioItinerario, itinerario: '', dia: ''}
    
circular_api_get_horario_seguinte_itinerario:
    pattern: /horarios/{itinerario}/seguinte/{hora}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getHorarioSeguinteItinerario, itinerario: '', hora: ''}

## FIM API INTERNA ##