#pais : 
#  type: rest
#  resource:     "CircularSiteBundle:PaisRest"
#  name_prefix:  api_

circular_api_get_token:
    pattern: /{id}/token/{tipo}
    defaults: {_controller: ApiBundle:CircularRest:getToken}
  
circular_api_get_dados:
    pattern: /recebe-dados/{hash}/{data}/{id}
    defaults: {_controller: ApiBundle:CircularRest:getDados, id: -1}
    
circular_api_set_dados:
    pattern: /envia-dados/{hash}
    defaults: {method: POST, _controller: ApiBundle:CircularRest:setDados}
    
circular_api_valida_token:
    pattern: /valida-token
    defaults: {_controller: ApiBundle:CircularRest:validaToken}
    
circular_api_set_imagem:
    pattern: /envia-imagem/{hash}
    defaults: {method: POST, _controller: ApiBundle:CircularRest:setImagem}
    
circular_api_get_imagem:
    pattern: /recebe-imagem/{nome}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getImagem}
    
circular_api_get_preferencias:
    pattern: /recebe-preferencias/{id}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getPreferencias}

circular_api_get_empresas:
    pattern: /empresas/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getEmpresas, slug: ''}
    
circular_api_get_cidades:
    pattern: /cidades/{uf}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getCidades, uf: '', slug: ''}
    
circular_api_get_bairros:
    pattern: /bairros/{uf}/{cidade}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getBairros, uf: '', cidade: '', slug: ''}
    
circular_api_get_paradas:
    pattern: /paradas/{uf}/{cidade}/{bairro}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getParadas, uf: '', cidade: '', bairro: '', slug: ''}
    
circular_api_get_pontos_interesse:
    pattern: /pontos-interesse/{uf}/{cidade}/{bairro}/{slug}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getPontosInteresse, uf: '', cidade: '', bairro: '', slug: ''}
    
circular_api_get_itinerarios_parada:
    pattern: /paradas/{uf}/{cidade}/{bairro}/{slug}/itinerarios
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getItinerariosParada, uf: '', cidade: '', bairro: '', slug: ''}
    
circular_api_get_horarios_itinerario:
    pattern: /horarios/{itinerario}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getHorariosItinerario, itinerario: ''}
    
circular_api_get_proximo_horario_itinerario:
    pattern: /horarios/{itinerario}/proximo
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getProximoHorarioItinerario, itinerario: ''}
    
circular_api_get_horario_anterior_itinerario:
    pattern: /horarios/{itinerario}/anterior
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getHorarioAnteriorItinerario, itinerario: ''}
    
circular_api_valida_usuario:
    pattern: /valida-usuario
    defaults: {_controller: ApiBundle:CircularRest:validaUsuario}