#pais : 
#  type: rest
#  resource:     "CircularSiteBundle:PaisRest"
#  name_prefix:  api_

circular_api_get_token:
    pattern: /{id}/token
    defaults: {_controller: ApiBundle:CircularRest:getToken}
  
circular_api_get_dados:
    pattern: /recebe-dados/{hash}/{data}
    defaults: {_controller: ApiBundle:CircularRest:getDados}
    
circular_api_set_dados:
    pattern: /envia-dados/{hash}
    defaults: {method: POST, _controller: ApiBundle:CircularRest:setDados}
    
circular_api_valida_token:
    pattern: /valida-token
    defaults: {_controller: ApiBundle:CircularRest:validaToken}
    
circular_api_set_imagem:
    pattern: /envia-imagem/{hash}
    defaults: {method: POST, _controller: ApiBundle:CircularRest:setImagem}
    
circular_api_get_imagem:
    pattern: /recebe-imagem/{nome}
    defaults: {method: GET, _controller: ApiBundle:CircularRest:getImagem}