<?php

namespace ApiBundle\Entity\Repository;

/**
 * APITokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APITokenRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function validaToken($token){
        $qb = $this->createQueryBuilder('t')
                ->select('t')
                ->distinct()
                ->where('t.puroTexto = :token')
                ->andWhere('t.dataCriacao > :data')
                ->andWhere('t.dataValidacao IS NULL')
                ->addOrderBy('t.dataCriacao', 'DESC')
                ->setParameter('token', $token)
                ->setParameter('data', new \DateTime('-2 minutes'))
                ;
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function atualizaToken($token){
        $qb = $this->createQueryBuilder('t')
                ->update('ApiBundle:APIToken t')
                ->set('t.dataValidacao', ':data')
                ->where('t.puroTexto = :token')
                ->setParameter('token', $token)
                ->setParameter('data', new \DateTime())
                ;
        
        return $qb->getQuery()->execute();
        
    }
    
    public function listarTodosRESTAdmin($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('a')
                ->select('-1 AS id, a.identificadorUnico, a.dataCriacao, a.dataValidacao')
                ->distinct()
                ->where("a.dataValidacao > :ultimaAlteracao")
                //->andWhere("c.programadoPara IS NULL OR c.programadoPara <= :now")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('a.dataValidacao', 'DESC');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
