<?php

namespace ApiBundle\Entity\Repository;

/**
 * APITokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APITokenRepository extends \Doctrine\ORM\EntityRepository
{
}
