<?php

namespace ApiBundle\Entity\Repository;

/**
 * BairroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BairroRepository extends \Doctrine\ORM\EntityRepository
{
}
