<?php

namespace ApiBundle\Entity\Repository;

/**
 * CidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CidadeRepository extends \Doctrine\ORM\EntityRepository
{
}
