<?php

namespace ApiBundle\Entity\Repository;

/**
 * HistoricoSecaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricoSecaoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodosRESTAdmin($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('hs')
                ->select('hs.id, hs.ativo, hs.dataCadastro, hs.dataRecebimento, '
                        . 'hs.ultimaAlteracao, hs.programadoPara, IDENTITY(hs.usuarioCadastro) AS usuarioCadastro, '
                        . 'IDENTITY(hs.usuarioUltimaAlteracao) AS usuarioUltimaAlteracao, hs.tarifa, IDENTITY(hs.secao) AS secao')
                ->distinct()
                ->where("hs.ultimaAlteracao > :ultimaAlteracao")
                //->andWhere("c.programadoPara IS NULL OR c.programadoPara <= :now")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('hs.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('hs')
                ->select('hs.id, hs.ativo, hs.dataCadastro, hs.dataRecebimento, '
                        . 'hs.ultimaAlteracao, hs.programadoPara, IDENTITY(hs.usuarioCadastro) AS usuarioCadastro, '
                        . 'IDENTITY(hs.usuarioUltimaAlteracao) AS usuarioUltimaAlteracao, hs.tarifa, IDENTITY(hs.secao) AS secao')
                ->distinct()
                ->where("hs.ultimaAlteracao > :ultimaAlteracao")
                ->andWhere("hs.programadoPara IS NULL OR hs.programadoPara <= :now")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->setParameter('now', new \DateTime())
                ->addOrderBy('hs.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
