<?php

namespace ApiBundle\Entity\Repository;

/**
 * HorarioItinerarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioItinerarioRepository extends \Doctrine\ORM\EntityRepository
{
}
