<?php

namespace ApiBundle\Entity\Repository;

/**
 * ItinerarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItinerarioRepository extends \Doctrine\ORM\EntityRepository
{
}
