<?php

namespace ApiBundle\Entity\Repository;

/**
 * LogEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
