<?php

namespace ApiBundle\Entity\Repository;

/**
 * OnibusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OnibusRepository extends \Doctrine\ORM\EntityRepository
{
}
