<?php

namespace ApiBundle\Entity\Repository;

/**
 * ParadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParadaRepository extends \Doctrine\ORM\EntityRepository
{
}
