<?php

namespace ApiBundle\Entity\Repository;

/**
 * PontoInteresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PontoInteresseRepository extends \Doctrine\ORM\EntityRepository
{
}
