<?php

namespace ApiBundle\Entity\Repository;

/**
 * SecaoItinerarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecaoItinerarioRepository extends \Doctrine\ORM\EntityRepository
{
}
