<?php

namespace ApiBundle\Entity\Repository;

/**
 * UsuarioPreferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioPreferenciaRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso, $id){
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->distinct()
                ->where("u.ultimaAlteracao > :ultimaAlteracao")
                ->andWhere("u.usuario = :id")
                //->andWhere("p.ativo = 1")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->setParameter('id', $id)
                ->addOrderBy('u.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function listarTodosRESTsemData($limite = null, $id){
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->distinct()
                ->andWhere("u.usuario = :id")
                ->setParameter('id', $id)
                ->addOrderBy('u.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function listarPreferenciaSemData($limite = null, $id){
        $qb = $this->createQueryBuilder('u')
                ->select('u.preferencia')
                ->distinct()
                ->andWhere("u.usuario = :id")
                ->setParameter('id', $id)
                ->addOrderBy('u.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_OBJECT);
        
    }
    
}
