<?php

namespace ApiBundle\Entity\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodosRESTAdmin($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('u')
                ->select('u.id, u.enabled AS ativo, u.dataCadastro, u.dataRecebimento, '
                        . 'u.ultimaAlteracao, u.programadoPara, u.nome, u.email')
                ->distinct()
                ->where("u.ultimaAlteracao > :ultimaAlteracao")
                //->andWhere("p.programadoPara IS NULL OR p.programadoPara <= :now")
                //->andWhere("p.ativo = 1")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('u.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
